version: "3.9"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MY_SQL_ROOT_PASSWORD: root
    volumes:
      - /home/vagrant/datasql:/var/lib/mysql
  spring_app:
    container_name: tpachato
    image: tpachato
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
  
  